### ISSUE TITLE
More in depth install instructions

### ISSUE THREAD

**Issue by gbailey4** [thelabnyc/wagtail_blog#10]
Hi there, I've tried your install directions but when I log into Wagtail I don't see any blog section of the admin. What are the steps from starting virtualenv to getting this working?

Thanks! I'm still learning as I go, so my apologies if I missed something obvious.

**Comment by bufke** [comment]
Are you familiar with wagtail? When you create a page do you have an option for the Blog Index? From there you can add blog pages.
