### ISSUE TITLE
Named URL's

### ISSUE THREAD

**Issue by tomtom5152** [thelabnyc/wagtail_blog#12]
I strongly dislike putting any constant URL's in a template file such as [blog_post.html](https://github.com/thelabnyc/wagtail_blog/blob/master/blog/templates/blog/blog_post.html#L44) as I feel this leaves it open to the users implementation. Using the default instructions this will work fine, but if the user wants to change the blog URL then they need to change the template as well.

A better solution would be to use `name="blog_category"` and similar in [urls.py](https://github.com/thelabnyc/wagtail_blog/blob/master/blog/urls.py). This would allow for the standard Django `{% url "blog_category" cat.category.slug %}`to be used in templates.

**Comment by bufke** [comment]
Sounds good to me - would you be able to submit a pull request?

**Comment by bufke** [comment]
Thanks
