### ISSUE TITLE
RSS feeds

### ISSUE THREAD

**Issue by shacker** [thelabnyc/wagtail_blog#14]
The readme mentions native RSS support. I see feed definitions in views.py, but the feed views are not referenced  in the URLs, so they're effectively off-line. 

Default templates should probably also link to feed views or include [autodiscovery](http://www.petefreitag.com/item/384.cfm) meta tags for them.

**Comment by shacker** [comment]
Ah, I see what's happening here. You have defined a feed URL for LatestCategoryFeed, but not for LatestEntriesFeed (which is the most important one), since that one hangs off a wagtail view and is not part of your own URL definitions. Hmm.  Thinking about this...

**Comment by bufke** [comment]
Feel free to suggest changes - I usually end up having to customize each usage of this app anyway. But sane defaults are good.

**Comment by shacker** [comment]
Part of the challenge is that wagtail lets you stick a BlogIndex anywhere in the hierarchy, so we really have a multi-blog system here. That works for the most part, but makes it tough to define URL structures for feeds when the first part of the URL is unknown. We can't even guarantee that 'blog' is in the URL at all - these are all valid blog index URLs:

```
/blog
/teachers/joe/blog
/parents/mary
```

I'm thinking maybe any URL that ends with `feed` or `blogfeed` triggers a view that inspects the page type at the parent of that? So `/parents/mary/blogfeed` would inspect the page type of `/parents/mary`. If that's a BlogIndex, it would return a feed for that blog; else 404. Gets complicated quickly.

**Comment by shacker** [comment]
OK, here's the solution I came up with, in case you want it to incorporate it / provide better defaults. This version works for multiple blogs on the site at any path, dynamically creates the main title, link and description, uses BLOG_PAGINATION_PER_PAGE from settings if it exists for number of items, and truncates the number of words in item descriptions.

So that the URL is not tied to paths under /blog, add to the global urls.py (matching URLs ending with "rss")

```
from blog.views import LatestEntriesFeed
...
urlpatterns = patterns(
    '',
    # Generate RSS feeds for blogs
    url(r'(?P<blog_slug>[\w-]+)/rss.*/', LatestEntriesFeed(), name="latest_entries_feed"),
```

and in blog.views:

```

class LatestEntriesFeed(Feed):
    '''
    If a URL ends with "rss" try to find a matching BlogIndexPage
    and return its items.
    '''

    def get_object(self, request, blog_slug):
        return get_object_or_404(BlogIndexPage, slug=blog_slug)

    def title(self, blog):
        return blog.title

    def link(self, blog):
        return blog.full_url

    def description(self, blog):
        return blog.search_description

    def items(self, blog):
        num = getattr(settings, 'BLOG_PAGINATION_PER_PAGE', 10)
        return blog.get_descendants()[:num]

    def item_title(self, item):
        return item.title

    def item_description(self, item):
        return truncatewords(item.specific.body, 50)

    def item_link(self, item):
        return item.full_url
```

**Comment by bufke** [comment]
Ok, will review when I have some time.

**Comment by bufke** [comment]
Sorry it's taken so long for me to respond. Would you be up for submitting a pull request and unit test?

I'd like the idea of supporting more options with where things go on the tree, different urls, multiple blogs ect. I'm not sure I have time for it myself.

**Comment by shacker** [comment]
Ditto - sorry for response delay. I've moved on to another project and am not deep in wagtail land ATM, but will resume in a month or two. Feel free to manually paste in the code above, or I'll do a PR in a few months. Cheers!
