### ISSUE TITLE
Problems with wagtail 1.1

### ISSUE THREAD

**Issue by bufke** [thelabnyc/wagtail_blog#17]
Copy no longer works. Might be related to https://github.com/thelabnyc/wagtail_blog/issues/8

I'm clueless on this issue. `'tags' is an invalid keyword argument for this function`

**Comment by eysdre** [comment]
i have same problem
Django Version:	1.8.5
Exception Type:	TypeError
Exception Value:	
'tags' is an invalid keyword argument for this function
Exception Location:	/home/hosting_maximmb/projects/wag-iq/env/lib/python3.4/site-packages/django/db/models/base.py in __init__, line 480
Python Executable:	/home/hosting_maximmb/projects/wag-iq/env/bin/python
Python Version:	3.4.2

**Comment by bufke** [comment]
Fixed upstream in wagtail 1.2
