### ISSUE TITLE
Comments

### ISSUE THREAD

**Issue by bufke** [thelabnyc/wagtail_blog#2]
Support for Disqus or maybe some django commenting app? Both?

**Comment by BrendanBerkley** [comment]
[Super suspect link](http://www.datanyze.com/market-share/Disqus)

Out of that list, I recognize FB Connect, Disqus, LiveFyre, and IntenseDebate.

[Here's your super rad alternative.to list](http://alternativeto.net/software/disqus/?license=opensource)

Discourse as comments would be interesting, but heavy.

Disqus seems to have momentum. You hate Facebook but it'd be used. Having a Django app would be nice as well, though I don't know what kind of popularity they have.

**Comment by SkiftCreative** [comment]
I would like to kind of see support for google+ comments as well, which when used properly can be tracked with SEO. Where Disqus I don't think can be because the way they are loaded (I could be wrong). I may be able to help on that once I get up and going more with wagtail.

**Comment by bufke** [comment]
django-comments-xtd support is done. @SkiftCreative feel free to make a pull request for other comments. They should not show by default. I might add Disqus but it's really easy to just override the templates and insert Disqus comments anyway.
