### ISSUE TITLE
Missing installation steps in the documentation

### ISSUE THREAD

**Issue by zooming-tan** [thelabnyc/wagtail_blog#20]
When attempting to integrate the app to an **existing** Django project, I got the following error.

```bash
SystemCheckError: System check identified some issues:

ERRORS:
blog.BlogIndexPage.page_ptr: (fields.E300) Field defines a relation with model 'Page', which is either not installed, or is abstract.
blog.BlogPage.header_image: (fields.E300) Field defines a relation with model 'Image', which is either not installed, or is abstract.
blog.BlogPage.page_ptr: (fields.E300) Field defines a relation with model 'Page', which is either not installed, or is abstract.
blog.BlogPage.tags: (fields.E300) Field defines a relation with model 'Tag', which is either not installed, or is abstract.
blog.BlogPageTag.tag: (fields.E300) Field defines a relation with model 'Tag', which is either not installed, or is abstract.
```
It seems that there is a missing step in the install guide. Users must integrate Wagtail first (http://docs.wagtail.io/en/v1.2/getting_started/integrating_into_django.html) prior to step 2. And the 'blog' app should be added **after** all the Wagtail apps in the INSTALL_APPS. Hope that helps.

**Comment by bufke** [comment]
I updated the README. Make sense?

https://github.com/thelabnyc/wagtail_blog/commit/baa83b758a72ed8f4793375f6678710565f22b3c#diff-04c6e90faac2675aa89e2176d2eec7d8

**Comment by bufke** [comment]
Also thanks for pointing this out!
