### ISSUE TITLE
Blog Categories 404

### ISSUE THREAD

**Issue by sirrryankennedy** [thelabnyc/wagtail_blog#27]
Everything works fine, except blog categories. I get a 404 when clicking on any of the categories I've created. Raised by wagtail.wagtailcore.views.serve. urls.py looks fine too. Any ideas?

`urlpatterns = patterns('',
    url(r'^tag/(?P<tag>[-\w]+)/', views.tag_view, name="tag"),
    url(r'^category/(?P<category>[-\w]+)/feed/$', views.LatestCategoryFeed(), name="category_feed"),
    url(r'^category/(?P<category>[-\w]+)/', views.category_view, name="category"),
    url(r'^author/(?P<author>[-\w]+)/', views.author_view, name="author"),
    url(r'(?P<blog_slug>[\w-]+)/rss.*/',
        views.LatestEntriesFeed(),
        name="latest_entries_feed"),
    url(r'(?P<blog_slug>[\w-]+)/atom.*/',
        views.LatestEntriesFeedAtom(),
        name="latest_entries_feed_atom"),
)
`

**Comment by steveshead** [comment]
In case you're still following this, how did you fix this error?
