### ISSUE TITLE
'Blogs' variable

### ISSUE THREAD

**Issue by jasonwbullok** [thelabnyc/wagtail_blog#3]
The 'blogs' variable should be persistent in the blog_page.html template to allow for any logic related to all the blog posts.

**Comment by bufke** [comment]
Fixed via https://github.com/thelabnyc/wagtail_blog/commit/c630b57213f10bcc4064a0a883561ddb1a596d60

**Comment by jasonwbullok** [comment]
'Categories' variable is on the blog_page now but 'blogs' still seems to be absent

**Comment by bufke** [comment]
Fixed
