### ISSUE TITLE
`demo` is included in installed package

### ISSUE THREAD

**Issue by akx** [thelabnyc/wagtail_blog#33]
The `demo` package gets included into the installed package (i.e. into `site-packages`) since the [`packages` clause](https://github.com/thelabnyc/wagtail_blog/blob/98a21b3cf06ad0a506d850ecdf67f4ffbaaed2f4/setup.py#L12) doesn't tell the tooling not to include it.

I think that's not optimal :)

**Comment by bufke** [comment]
Could you submit a merge request to have it not part of the package?

**Comment by akx** [comment]
Done deal, @bufke. Sorry it took me a while to get back to doing that.
