### ISSUE TITLE
Blog category won't save

### ISSUE THREAD

**Issue by mukulrawat1986** [thelabnyc/wagtail_blog#7]

**Comment by mukulrawat1986** [comment]
Hi, I have been testing out wagtail_blog. When trying to create a new blog category and when trying to create a new blog category it fails giving the error, "The snippet could not be created due to errors."

**Comment by mukulrawat1986** [comment]
I was able to resolve this issue, by adding a field panel in blog categories for slug. Please note at present there is no field panel for slug in the BlogCategory model even though its defined there.

**Comment by bufke** [comment]
I was never able to reproduce this, are you using the most recent version of wagtail? Reopen if you think it's still a problem.
